services:
  - type: web
    name: medicare-backend
    env: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

